### ISSUE TITLE
When loaded data is updated, cardsliders disappear 

### ISSUE THREAD

**Issue by braulio94** [Ramotion/cardslider-android#11]
I'm using FirebaseUI Library to get images from my database to appear on the cardslider, and it works perfectly. But whenever I update that data or add a new item, cardsliders disapear and doesn't come back unless I close my app and reopen it.

What might be wrong? Any idea? Thank you.

**Comment by dvg4000** [comment]
Yes, there is a bug. I will try to fix it soon.

**Comment by braulio94** [comment]
is it fix already? Thank you so much!

**Comment by braulio94** [comment]
@dvg4000 is there going to an update?

**Comment by dvg4000** [comment]
@braulio94 version updated

**Comment by braulio94** [comment]
it took a while
