### ISSUE TITLE
How to set card width and height 100%

### ISSUE THREAD

**Issue by ahmadalibaloch** [Ramotion/cardslider-android#12]
I want to show cards as full screen or 95%. How can I give width and height programmatically in percentage?

**Comment by braulio94** [comment]
You can use "cardWidth" change the width of the cards:

```
<android.support.v7.widget.RecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:cardWidth="300dp"
        />
```

and the height of the cards is determined by the recyclerview's height
Hope this helps.

**Comment by ahmadalibaloch** [comment]
@braulio94 Well, I asked programmatically cause I am using realmRecycleView.

**Comment by dvg4000** [comment]
@ahmadalibaloch, you can set card width in pixels, programmatically, with this constructor:
`... = new CardSliderLayoutManager(offset, cardWidth, cardsGap);`

>the height of the cards is determined by the recyclerview's height

**Comment by ahmadalibaloch** [comment]
I know... but for different screen sizes and orientations on the devices, I want to set it in percentage or `match_parent`, yet programmatically!

**Comment by MicroRJ** [comment]
Try this. https://stackoverflow.com/q/10310550/8736759

**Comment by omidraha** [comment]
@ahmadalibaloch Do you find the answer?

**Comment by ahmadalibaloch** [comment]
NO! I stopped using this lib.

**Comment by Moosphan** [comment]
@ahmadalibaloch Can you recommend another similar lib?

**Comment by ahmadalibaloch** [comment]
@Moosphan I used this ItemDecoration for Android Recyclerview https://github.com/bleeding182/recyclerviewItemDecorations

**Comment by Moosphan** [comment]
@ahmadalibaloch thanks a lot😁

**Comment by golovin47** [comment]
Hello, @ahmadalibaloch. You can apply your preferred height to cards using @dvg4000 proposed approach. If you need to set card's height as available screen height (or some percent of it), you can get the screen height with this code:

Display display = getWindowManager().getDefaultDisplay();
Point size = new Point();
display.getSize(size);
int width = size.x;
int height = size.y; 

getWindowManager() is one of the Context class methods, so it should be called inside context class (Activity for example) or you can provide a reference to context in any way you prefer.

**Comment by lalit12334** [comment]
> = new CardSliderLayoutManager(offset, cardWidth, cardsGap);

when i add all these parameter the animation get lost in slider  how to fix it
