### ISSUE TITLE
Is there any way to make the main card in center?

### ISSUE THREAD

**Issue by chnouman** [Ramotion/cardslider-android#13]
actually i want the main card to be in center and from both sides i.e left and right it should be look same as it is now in right side.
Let me know if you don't understand my question please!

**Comment by braulio94** [comment]
I would suggest you use [this](https://github.com/Ramotion/expanding-collection-android) library by Ramotion that does exactly that.

**Comment by chnouman** [comment]
hy @braulio94  thanks dear i want to create this in swift for ios can you have any reference link.

**Comment by braulio94** [comment]
try [this](https://github.com/Ramotion/expanding-collection)

**Comment by omidraha** [comment]
Is there any solution for [cardslider-android](https://github.com/Ramotion/cardslider-android) ?

**Comment by golovin47** [comment]
Hello. Currently cardslider-android doesn't have such feature. But you can implement it yourself by customizing source code of this lib.
