### ISSUE TITLE
Why my App with same code is lagging?

### ISSUE THREAD

**Issue by saichandu415** [Ramotion/cardslider-android#14]
i have took the latest sample code base and build it as an seperate project but i see the app is very laggy but the app which you have created is smooth while scrolling. 
what I should have forgotten while making the new project?

**Note**: I copy pasted all the java code and dependencies from cardslider demo app
Any help is appreciated

**Comment by golovin47** [comment]
Hello, @saichandu415. If you have copied absolutely all the source code from cardslider-android, then it should work just fine. if it is lagging try to compare it with what we have in the lib and in example project.
