### ISSUE TITLE
Please provide documentation

### ISSUE THREAD

**Issue by bryan-ibrahim** [Ramotion/cardslider-android#18]
I have been trying to implement this library for a while now(close to a month now), have trying adding it as a library, as a module, but always get errors. For instance - it throws an error-> Unable to find ViewUpdater as soon as the app launches.

I will really appreciate any help.

**Comment by dvg4000** [comment]
Maybe this will help: https://github.com/Ramotion/cardslider-android/issues/16

**Comment by dvg4000** [comment]
@bryan-ibrahim, can you provide more error logs?

**Comment by bryan-ibrahim** [comment]
![log](https://user-images.githubusercontent.com/17259341/35473924-f113ac56-0397-11e8-9b91-12febbf0107c.PNG)

**Comment by Eun0** [comment]
+1

**Comment by ibolat38** [comment]
I am getting same error.. Please how can we fix this ? @dvg4000

**Comment by dvg4000** [comment]
Maybe you use example's `CardsUpdater`? Check this line in your layour.xml file: `app:viewUpdater="com.ramotion.cardslider.examples.simple.cards.CardsUpdater"`. If you have it, just remove it or change to your local `CardsUpdater`.

**Comment by bryan-ibrahim** [comment]
Yes, that was the problem
