### ISSUE TITLE
How can use vertical? 

### ISSUE THREAD

**Issue by pdog18** [Ramotion/cardslider-android#21]

**Comment by gsrathoreniks** [comment]
@pdog18 This Library is written for horizontally working recycler view, you can make changes according to vertically showing cards.

**Comment by hefuyicoder** [comment]
@gsrathoreniks hello,I have try to make changes the CardSliderLayoutManager according to vertically showing cards,now it can scroll vertically ,but there's a problem , not scroll fluently,I take a long time to resolve it ,but no result ,can you help me to point out the error? Thanks a lot .Here is the gist [CardSliderLayoutManager ](https://gist.github.com/hefuyicoder/ea011252c88b967054da29f829aead7c)

**Comment by hefuyicoder** [comment]
@dvg4000 can you help me ?

**Comment by golovin47** [comment]
Hello. Right now there is no such feature in cardslider-android. But you can achieve such behavior by customizing this lib source code.
