### ISSUE TITLE
Search functionality (Question)

### ISSUE THREAD

**Issue by HIREN4131KINAL** [Ramotion/cardslider-android#23]
I implemented search functionality in cardslider for to search specific card by name or etc.. and its working properly but when i slide one or some cards i am unable to show images. So, whats am i doing wrong? can you help me?

**Comment by singhgautam7** [comment]
I don't know the answer to your question, but can you please review issue number #24 here, i have been stuck on it

**Comment by gsrathoreniks** [comment]
@HIREN4131KINAL can you share your project?

**Comment by HIREN4131KINAL** [comment]
Thanks guys for your reply and I have solved my issue.
