### ISSUE TITLE
How to get position of curremt selected item?

### ISSUE THREAD

**Issue by singhgautam7** [Ramotion/cardslider-android#24]

**Comment by gsrathoreniks** [comment]
Hello @TheNakedDeveloper,
Follow these steps,

1. Open MainActivity.java
2. navigate to the function `onActiveCardChange()`
3. see `final int pos = layoutManger.getActiveCardPosition();`
4. Here you're getting position of the current Item in Integer `pos`.

I think you were looking for this, let me know if you're still confused.
