### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by bkhezry** [Ramotion/cardslider-android#25]
Hi,
I just change layoutDirection of recycler view to rtl but this option didn't support in the CardSliderLayoutManager. how can I add this feature?

**Comment by golovin47** [comment]
Hello, @bkhezry. Right now there is no such feature in cardslider-android. If you need RTL, you customize the source code of this lib. Try inverting some of the values, responsible for laying out the cards in layout manager.

**Comment by AliBakrey** [comment]
Hello, @golovin47 Could you mention for any functions we need to change
