### ISSUE TITLE
Any reason why the minimum api level is kitkat?

### ISSUE THREAD

**Issue by raylee4204** [Ramotion/cardslider-android#3]

**Comment by eneim** [comment]
@raylee4204 may be [this](https://github.com/Ramotion/cardslider-android/blob/master/card-slider/src/main/java/com/ramotion/cardslider/CardSliderLayoutManager.java#L360) (multi catch is not supported in SDK 16 ...). But hey this is just silly :D. So maybe some other places :D.

**Comment by jonathansds** [comment]
I'd like like to know as well. I'm actually thinking twice if I use this library or implement my own one cause my project uses API level 16+ and I don't feel like changing to 19+ just because of 1 single lib.
Any reason the minimum API level is Kitkat?

**Comment by eneim** [comment]
@jonathansds you can clone this and manually add it into your library, make sure to mention the license (this one is a Apache 2.0 so it will be fine). as you also know about my lib, take a look on how I'm using it maybe helpful :p

**Comment by jonathansds** [comment]
Hi @eneim I will as you suggest then :) Thanks.
Can you provide a link of the file you're using the library?

Thanks.

**Comment by jonathansds** [comment]
Also, @eneim what about use `<uses-sdk android:minSdkVersion="16" tools:overrideLibrary="com.ramotion.cardslider"/>` ? Have you tried it? Do you think it worth a try?

**Comment by eneim** [comment]
@jonathansds This link is where I custom this [click here](https://github.com/eneim/toro/blob/dev-v3/app/src/main/java/com/ramotion/cardslider/CardSliderLayoutManager.java#L362). I just change the way it catches the exception ...

**Comment by eneim** [comment]
Also the override will not make it to Jellybean user I suppose.
