### ISSUE TITLE
How to turn off the scroll effect

### ISSUE THREAD

**Issue by ianeinser** [Ramotion/cardslider-android#32]
Hi, do you know how to turn off the scroll effect but the card is still clickable and has zoom in/out effect? I appreciate for the pointer

**Comment by golovin47** [comment]
Hi, @ianeinser. There are DefaultViewUpdater, CardSnapHelper and CardSliderLayoutManager classes which you need to modify to achieve any behavior you need. Play around with various properties in those classes.
