### ISSUE TITLE
Scrolling Delete Card Positioning

### ISSUE THREAD

**Issue by edgarscr** [Ramotion/cardslider-android#34]
Hello how are you? 

When you scroll all cards to left and delete de active card the scroll position dont update example in photo

![image](https://user-images.githubusercontent.com/33737821/66788609-d9a91300-eead-11e9-96bd-59089fafa952.png)

can you help me or tell me what i can do for that?

**Comment by golovin47** [comment]
Hello, @edgarscr. Look closer to library example implementation. You may try to change it to acquire behavior you need. When it will behave the way you need apply it to your project.

**Comment by edgarscr** [comment]
Hello, my problem its this look normal recycler view cards

![image](https://user-images.githubusercontent.com/33737821/66857382-c7ca7d00-ef4c-11e9-9b67-4c041827e698.png)

scrolling work perfect

but if i scroll all to right 

![image](https://user-images.githubusercontent.com/33737821/66857442-e4ff4b80-ef4c-11e9-84a3-d64425936c62.png)


Looks like that, but if i remove one card (last) they stay like this

![image](https://user-images.githubusercontent.com/33737821/66857478-f6e0ee80-ef4c-11e9-84d9-ded7586a1cf6.png)

but i search in ur documentation and dont found nothing to help .

**Comment by golovin47** [comment]
This feature is specific to your project so you'll need to figure out how to implement it. If you'll need then you can fork this lib and customize it the way you need.
