### ISSUE TITLE
CardWidth is not working

### ISSUE THREAD

**Issue by max02100** [Ramotion/cardslider-android#5]
in my layout : 
`<android.support.v7.widget.RecyclerView
            android:id="@+id/pileLayout"
            android:layout_width="match_parent"
            android:layout_height="250dp"
            android:layout_below="@+id/textview_wod_quantity"
            android:layout_marginBottom="16dp"
            android:layout_marginTop="32dp"
            android:clipChildren="false"
            android:overScrollMode="never"
            app:layoutManager="com.ramotion.cardslider.CardSliderLayoutManager"
            app:viewUpdater="com.mvince.wodrandom.ui.customView.CardsUpdater"
            app:cardWidth="400dp"/>`

the cardWith is set but not effective in the app

**Comment by dvg4000** [comment]
Cant reproduce. It works in example.

**Comment by pfieffer** [comment]
I am facing the same issue, I even tried setting item width, height to `match_parent` as it is done in the sample. The `app:cardWidth` attribute works in the xml preview but not when ran in the app.
Seems like this works only in the sample.
